### ISSUE TITLE
Accessibility for Newbies

### ISSUE THREAD

**Issue by Magenta-6** [zackees/zcmds#3]
I discovered your repo thru your interview with Mike Adams.

As you know writing code is (in the minds of most people) an esoteric dark science.
To make it more accessible to a wider group and to get newbies started . . . 
and in the interests of reducing the significant barriers to having fun with repositories - is there any chance you could expand your notes to your readme.md about 1) how to install  and 2) how to use one or two of the tools.

INSTALLATION IN WINDOWS
Chose a location on your hard drive to install the repository. 
It does not have to be on your C:\drive - it could be on a separate drive.
It makes sense to have a folder for Git Repositories - lets call it "Git"
Highlight the folder in windows and in the address field type "cmd"
This opens windows command-line.

In the command-line window Type>pip install zcmds                                - NOT zmcds!!!!
This installs the repo and pulls all the requirements needed to run the sub-programs

EXAMPLE: CONVERT AN IMAGE TO WEBP FORMAT
For example if you wanted to convert an image from a .png to .webp
In Windows
1.   Create a folder in a convenient location - say E:\Git\zcmds - lets call the new folder "input"
2.   Load image files you want to convert. (Consider renaming them or not)
3.   Create an output folder - lets call it "output"
4.   Navigate to the repository and in the address-bar type "cmd"
In the command-line E:\Git\zcmds>
5.   type   >img2webp input E:\Git\zcmds\input\image-001.jpg --format webp --output E:\Git\zcmds\output

6.   To access Help with this command type >img2webp -h

**Comment by uberhacker** [comment]
I saw the interview with Mike Adams too.  It was mind-blowing!
